apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resourcequota.yaml
  - networkpolicies.yaml
  - external-secret.yaml
  - configmap.yaml
  - postgres.yaml
  - hazelcast-jmx-exporter-configmap.yaml
  - hazelcast-deployment.yaml
  - hazelcast-service.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml
  - gateway.yaml

images:
  - name: message-service
    newName: us-central1-docker.pkg.dev/k8s-dev-412419/springboot-grpc-o2/grpc-message-api
    newTag: latest
